# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import images
import bk
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.Gamespace = QtWidgets.QGroupBox(self.centralwidget)
        self.Gamespace.setGeometry(QtCore.QRect(10, 10, 1171, 441))
        self.Gamespace.setTitle("")
        self.Gamespace.setObjectName("Gamespace")
        self.submit_button = QtWidgets.QPushButton(self.Gamespace)
        self.submit_button.setGeometry(QtCore.QRect(880, 390, 93, 28))
        self.submit_button.setObjectName("submit_button")
        self.line = QtWidgets.QFrame(self.Gamespace)
        self.line.setGeometry(QtCore.QRect(20, 360, 1101, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.question_button = QtWidgets.QPushButton(self.Gamespace)
        self.question_button.setGeometry(QtCore.QRect(30, 390, 93, 28))
        self.question_button.setObjectName("question_button")
        self.mode_button = QtWidgets.QPushButton(self.Gamespace)
        self.mode_button.setGeometry(QtCore.QRect(150, 390, 93, 28))
        self.mode_button.setObjectName("mode_button")
        self.showanswer_button = QtWidgets.QPushButton(self.Gamespace)
        self.showanswer_button.setGeometry(QtCore.QRect(1000, 390, 93, 28))
        self.showanswer_button.setObjectName("showanswer_button")
        self.equal_0 = QtWidgets.QGroupBox(self.Gamespace)
        self.equal_0.setGeometry(QtCore.QRect(20, 60, 121, 261))
        self.equal_0.setTitle("")
        self.equal_0.setObjectName("equal_0")
        self.pos_0_5 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_5.setGeometry(QtCore.QRect(0, 150, 20, 91))
        self.pos_0_5.setAcceptDrops(False)
        self.pos_0_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Match.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pos_0_5.setIcon(icon)
        self.pos_0_5.setIconSize(QtCore.QSize(15, 80))
        self.pos_0_5.setAutoRepeat(False)
        self.pos_0_5.setAutoExclusive(False)
        self.pos_0_5.setObjectName("pos_0_5")
        self.pos_0_3 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_3.setGeometry(QtCore.QRect(100, 150, 20, 91))
        self.pos_0_3.setAcceptDrops(False)
        self.pos_0_3.setText("")
        self.pos_0_3.setIcon(icon)
        self.pos_0_3.setIconSize(QtCore.QSize(15, 80))
        self.pos_0_3.setAutoRepeat(False)
        self.pos_0_3.setAutoExclusive(False)
        self.pos_0_3.setObjectName("pos_0_3")
        self.pos_0_1 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_1.setGeometry(QtCore.QRect(20, 6, 81, 20))
        self.pos_0_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("match_heng.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pos_0_1.setIcon(icon1)
        self.pos_0_1.setIconSize(QtCore.QSize(65, 30))
        self.pos_0_1.setObjectName("pos_0_1")
        self.pos_0_6 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_6.setGeometry(QtCore.QRect(0, 30, 20, 101))
        self.pos_0_6.setAcceptDrops(False)
        self.pos_0_6.setText("")
        self.pos_0_6.setIcon(icon)
        self.pos_0_6.setIconSize(QtCore.QSize(15, 80))
        self.pos_0_6.setAutoRepeat(False)
        self.pos_0_6.setAutoExclusive(False)
        self.pos_0_6.setObjectName("pos_0_6")
        self.pos_0_2 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_2.setGeometry(QtCore.QRect(100, 30, 20, 101))
        self.pos_0_2.setAcceptDrops(False)
        self.pos_0_2.setText("")
        self.pos_0_2.setIcon(icon)
        self.pos_0_2.setIconSize(QtCore.QSize(15, 80))
        self.pos_0_2.setAutoRepeat(False)
        self.pos_0_2.setAutoExclusive(False)
        self.pos_0_2.setObjectName("pos_0_2")
        self.pos_0_7 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_7.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pos_0_7.setText("")
        self.pos_0_7.setIcon(icon1)
        self.pos_0_7.setIconSize(QtCore.QSize(65, 30))
        self.pos_0_7.setObjectName("pos_0_7")
        self.pos_0_4 = QtWidgets.QPushButton(self.equal_0)
        self.pos_0_4.setGeometry(QtCore.QRect(20, 230, 81, 20))
        self.pos_0_4.setText("")
        self.pos_0_4.setIcon(icon1)
        self.pos_0_4.setIconSize(QtCore.QSize(65, 30))
        self.pos_0_4.setObjectName("pos_0_4")
        self.equal_1 = QtWidgets.QGroupBox(self.Gamespace)
        self.equal_1.setGeometry(QtCore.QRect(160, 60, 121, 261))
        self.equal_1.setTitle("")
        self.equal_1.setObjectName("equal_1")
        self.pos_1_5 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_5.setGeometry(QtCore.QRect(0, 150, 20, 91))
        self.pos_1_5.setAcceptDrops(False)
        self.pos_1_5.setText("")
        self.pos_1_5.setIcon(icon)
        self.pos_1_5.setIconSize(QtCore.QSize(15, 80))
        self.pos_1_5.setAutoRepeat(False)
        self.pos_1_5.setAutoExclusive(False)
        self.pos_1_5.setObjectName("pos_1_5")
        self.pos_1_3 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_3.setGeometry(QtCore.QRect(100, 150, 20, 91))
        self.pos_1_3.setAcceptDrops(False)
        self.pos_1_3.setText("")
        self.pos_1_3.setIcon(icon)
        self.pos_1_3.setIconSize(QtCore.QSize(15, 80))
        self.pos_1_3.setAutoRepeat(False)
        self.pos_1_3.setAutoExclusive(False)
        self.pos_1_3.setObjectName("pos_1_3")
        self.pos_1_1 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_1.setGeometry(QtCore.QRect(20, 6, 81, 20))
        self.pos_1_1.setText("")
        self.pos_1_1.setIcon(icon1)
        self.pos_1_1.setIconSize(QtCore.QSize(65, 30))
        self.pos_1_1.setObjectName("pos_1_1")
        self.pos_1_6 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_6.setGeometry(QtCore.QRect(0, 30, 20, 101))
        self.pos_1_6.setAcceptDrops(False)
        self.pos_1_6.setText("")
        self.pos_1_6.setIcon(icon)
        self.pos_1_6.setIconSize(QtCore.QSize(15, 80))
        self.pos_1_6.setAutoRepeat(False)
        self.pos_1_6.setAutoExclusive(False)
        self.pos_1_6.setObjectName("pos_1_6")
        self.pos_1_2 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_2.setGeometry(QtCore.QRect(100, 30, 20, 101))
        self.pos_1_2.setAcceptDrops(False)
        self.pos_1_2.setText("")
        self.pos_1_2.setIcon(icon)
        self.pos_1_2.setIconSize(QtCore.QSize(15, 80))
        self.pos_1_2.setAutoRepeat(False)
        self.pos_1_2.setAutoExclusive(False)
        self.pos_1_2.setObjectName("pos_1_2")
        self.pos_1_7 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_7.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pos_1_7.setText("")
        self.pos_1_7.setIcon(icon1)
        self.pos_1_7.setIconSize(QtCore.QSize(65, 30))
        self.pos_1_7.setObjectName("pos_1_7")
        self.pos_1_4 = QtWidgets.QPushButton(self.equal_1)
        self.pos_1_4.setGeometry(QtCore.QRect(20, 230, 81, 20))
        self.pos_1_4.setText("")
        self.pos_1_4.setIcon(icon1)
        self.pos_1_4.setIconSize(QtCore.QSize(65, 30))
        self.pos_1_4.setObjectName("pos_1_4")
        self.equal_2 = QtWidgets.QTabWidget(self.Gamespace)
        self.equal_2.setGeometry(QtCore.QRect(300, 60, 131, 261))
        self.equal_2.setObjectName("equal_2")
        self.plus_minus = QtWidgets.QWidget()
        self.plus_minus.setObjectName("plus_minus")
        self.sig_0 = QtWidgets.QPushButton(self.plus_minus)
        self.sig_0.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.sig_0.setText("")
        self.sig_0.setIcon(icon1)
        self.sig_0.setIconSize(QtCore.QSize(65, 30))
        self.sig_0.setObjectName("sig_0")
        self.sig_1 = QtWidgets.QPushButton(self.plus_minus)
        self.sig_1.setGeometry(QtCore.QRect(50, 60, 20, 101))
        self.sig_1.setAcceptDrops(False)
        self.sig_1.setText("")
        self.sig_1.setIcon(icon)
        self.sig_1.setIconSize(QtCore.QSize(15, 80))
        self.sig_1.setAutoRepeat(False)
        self.sig_1.setAutoExclusive(False)
        self.sig_1.setObjectName("sig_1")
        self.sig_1.raise_()
        self.sig_0.raise_()
        self.equal_2.addTab(self.plus_minus, "")
        self.mutiply = QtWidgets.QWidget()
        self.mutiply.setObjectName("mutiply")
        self.sig_3_4 = QtWidgets.QPushButton(self.mutiply)
        self.sig_3_4.setGeometry(QtCore.QRect(30, 50, 61, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.sig_3_4.setFont(font)
        self.sig_3_4.setAcceptDrops(False)
        self.sig_3_4.setIconSize(QtCore.QSize(15, 80))
        self.sig_3_4.setAutoRepeat(False)
        self.sig_3_4.setAutoExclusive(False)
        self.sig_3_4.setObjectName("sig_3_4")
        self.equal_2.addTab(self.mutiply, "")
        self.equal_3 = QtWidgets.QGroupBox(self.Gamespace)
        self.equal_3.setGeometry(QtCore.QRect(440, 60, 121, 261))
        self.equal_3.setTitle("")
        self.equal_3.setObjectName("equal_3")
        self.pos_3_5 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_5.setGeometry(QtCore.QRect(0, 150, 20, 91))
        self.pos_3_5.setAcceptDrops(False)
        self.pos_3_5.setText("")
        self.pos_3_5.setIcon(icon)
        self.pos_3_5.setIconSize(QtCore.QSize(15, 80))
        self.pos_3_5.setAutoRepeat(False)
        self.pos_3_5.setAutoExclusive(False)
        self.pos_3_5.setObjectName("pos_3_5")
        self.pos_3_3 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_3.setGeometry(QtCore.QRect(100, 150, 20, 91))
        self.pos_3_3.setAcceptDrops(False)
        self.pos_3_3.setText("")
        self.pos_3_3.setIcon(icon)
        self.pos_3_3.setIconSize(QtCore.QSize(15, 80))
        self.pos_3_3.setAutoRepeat(False)
        self.pos_3_3.setAutoExclusive(False)
        self.pos_3_3.setObjectName("pos_3_3")
        self.pos_3_1 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_1.setGeometry(QtCore.QRect(20, 6, 81, 20))
        self.pos_3_1.setText("")
        self.pos_3_1.setIcon(icon1)
        self.pos_3_1.setIconSize(QtCore.QSize(65, 30))
        self.pos_3_1.setObjectName("pos_3_1")
        self.pos_3_6 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_6.setGeometry(QtCore.QRect(0, 30, 20, 101))
        self.pos_3_6.setAcceptDrops(False)
        self.pos_3_6.setText("")
        self.pos_3_6.setIcon(icon)
        self.pos_3_6.setIconSize(QtCore.QSize(15, 80))
        self.pos_3_6.setAutoRepeat(False)
        self.pos_3_6.setAutoExclusive(False)
        self.pos_3_6.setObjectName("pos_3_6")
        self.pos_3_2 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_2.setGeometry(QtCore.QRect(100, 30, 20, 101))
        self.pos_3_2.setAcceptDrops(False)
        self.pos_3_2.setText("")
        self.pos_3_2.setIcon(icon)
        self.pos_3_2.setIconSize(QtCore.QSize(15, 80))
        self.pos_3_2.setAutoRepeat(False)
        self.pos_3_2.setAutoExclusive(False)
        self.pos_3_2.setObjectName("pos_3_2")
        self.pos_3_7 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_7.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pos_3_7.setText("")
        self.pos_3_7.setIcon(icon1)
        self.pos_3_7.setIconSize(QtCore.QSize(65, 30))
        self.pos_3_7.setObjectName("pos_3_7")
        self.pos_3_4 = QtWidgets.QPushButton(self.equal_3)
        self.pos_3_4.setGeometry(QtCore.QRect(20, 230, 81, 20))
        self.pos_3_4.setText("")
        self.pos_3_4.setIcon(icon1)
        self.pos_3_4.setIconSize(QtCore.QSize(65, 30))
        self.pos_3_4.setObjectName("pos_3_4")
        self.equal_4 = QtWidgets.QGroupBox(self.Gamespace)
        self.equal_4.setGeometry(QtCore.QRect(580, 60, 121, 261))
        self.equal_4.setTitle("")
        self.equal_4.setObjectName("equal_4")
        self.pos_4_5 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_5.setGeometry(QtCore.QRect(0, 150, 20, 91))
        self.pos_4_5.setAcceptDrops(False)
        self.pos_4_5.setText("")
        self.pos_4_5.setIcon(icon)
        self.pos_4_5.setIconSize(QtCore.QSize(15, 80))
        self.pos_4_5.setAutoRepeat(False)
        self.pos_4_5.setAutoExclusive(False)
        self.pos_4_5.setObjectName("pos_4_5")
        self.pos_4_3 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_3.setGeometry(QtCore.QRect(100, 150, 20, 91))
        self.pos_4_3.setAcceptDrops(False)
        self.pos_4_3.setText("")
        self.pos_4_3.setIcon(icon)
        self.pos_4_3.setIconSize(QtCore.QSize(15, 80))
        self.pos_4_3.setAutoRepeat(False)
        self.pos_4_3.setAutoExclusive(False)
        self.pos_4_3.setObjectName("pos_4_3")
        self.pos_4_1 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_1.setGeometry(QtCore.QRect(20, 6, 81, 20))
        self.pos_4_1.setText("")
        self.pos_4_1.setIcon(icon1)
        self.pos_4_1.setIconSize(QtCore.QSize(65, 30))
        self.pos_4_1.setObjectName("pos_4_1")
        self.pos_4_6 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_6.setGeometry(QtCore.QRect(0, 30, 20, 101))
        self.pos_4_6.setAcceptDrops(False)
        self.pos_4_6.setText("")
        self.pos_4_6.setIcon(icon)
        self.pos_4_6.setIconSize(QtCore.QSize(15, 80))
        self.pos_4_6.setAutoRepeat(False)
        self.pos_4_6.setAutoExclusive(False)
        self.pos_4_6.setObjectName("pos_4_6")
        self.pos_4_2 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_2.setGeometry(QtCore.QRect(100, 30, 20, 101))
        self.pos_4_2.setAcceptDrops(False)
        self.pos_4_2.setText("")
        self.pos_4_2.setIcon(icon)
        self.pos_4_2.setIconSize(QtCore.QSize(15, 80))
        self.pos_4_2.setAutoRepeat(False)
        self.pos_4_2.setAutoExclusive(False)
        self.pos_4_2.setObjectName("pos_4_2")
        self.pos_4_7 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_7.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pos_4_7.setText("")
        self.pos_4_7.setIcon(icon1)
        self.pos_4_7.setIconSize(QtCore.QSize(65, 30))
        self.pos_4_7.setObjectName("pos_4_7")
        self.pos_4_4 = QtWidgets.QPushButton(self.equal_4)
        self.pos_4_4.setGeometry(QtCore.QRect(20, 230, 81, 20))
        self.pos_4_4.setText("")
        self.pos_4_4.setIcon(icon1)
        self.pos_4_4.setIconSize(QtCore.QSize(65, 30))
        self.pos_4_4.setObjectName("pos_4_4")
        self.dengyu = QtWidgets.QGroupBox(self.Gamespace)
        self.dengyu.setGeometry(QtCore.QRect(720, 60, 121, 261))
        self.dengyu.setTitle("")
        self.dengyu.setObjectName("dengyu")
        self.pushButton_59 = QtWidgets.QPushButton(self.dengyu)
        self.pushButton_59.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.pushButton_59.setText("")
        self.pushButton_59.setIcon(icon1)
        self.pushButton_59.setIconSize(QtCore.QSize(65, 30))
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(self.dengyu)
        self.pushButton_60.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pushButton_60.setText("")
        self.pushButton_60.setIcon(icon1)
        self.pushButton_60.setIconSize(QtCore.QSize(65, 30))
        self.pushButton_60.setObjectName("pushButton_60")
        self.equal_5 = QtWidgets.QGroupBox(self.Gamespace)
        self.equal_5.setGeometry(QtCore.QRect(860, 50, 121, 261))
        self.equal_5.setTitle("")
        self.equal_5.setObjectName("equal_5")
        self.pos_5_5 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_5.setGeometry(QtCore.QRect(0, 150, 20, 91))
        self.pos_5_5.setAcceptDrops(False)
        self.pos_5_5.setText("")
        self.pos_5_5.setIcon(icon)
        self.pos_5_5.setIconSize(QtCore.QSize(15, 80))
        self.pos_5_5.setAutoRepeat(False)
        self.pos_5_5.setAutoExclusive(False)
        self.pos_5_5.setObjectName("pos_5_5")
        self.pos_5_3 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_3.setGeometry(QtCore.QRect(100, 150, 20, 91))
        self.pos_5_3.setAcceptDrops(False)
        self.pos_5_3.setText("")
        self.pos_5_3.setIcon(icon)
        self.pos_5_3.setIconSize(QtCore.QSize(15, 80))
        self.pos_5_3.setAutoRepeat(False)
        self.pos_5_3.setAutoExclusive(False)
        self.pos_5_3.setObjectName("pos_5_3")
        self.pos_5_1 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_1.setGeometry(QtCore.QRect(20, 6, 81, 20))
        self.pos_5_1.setText("")
        self.pos_5_1.setIcon(icon1)
        self.pos_5_1.setIconSize(QtCore.QSize(65, 30))
        self.pos_5_1.setObjectName("pos_5_1")
        self.pos_5_6 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_6.setGeometry(QtCore.QRect(0, 30, 20, 101))
        self.pos_5_6.setAcceptDrops(False)
        self.pos_5_6.setText("")
        self.pos_5_6.setIcon(icon)
        self.pos_5_6.setIconSize(QtCore.QSize(15, 80))
        self.pos_5_6.setAutoRepeat(False)
        self.pos_5_6.setAutoExclusive(False)
        self.pos_5_6.setObjectName("pos_5_6")
        self.pos_5_2 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_2.setGeometry(QtCore.QRect(100, 30, 20, 101))
        self.pos_5_2.setAcceptDrops(False)
        self.pos_5_2.setText("")
        self.pos_5_2.setIcon(icon)
        self.pos_5_2.setIconSize(QtCore.QSize(15, 80))
        self.pos_5_2.setAutoRepeat(False)
        self.pos_5_2.setAutoExclusive(False)
        self.pos_5_2.setObjectName("pos_5_2")
        self.pos_5_7 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_7.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pos_5_7.setText("")
        self.pos_5_7.setIcon(icon1)
        self.pos_5_7.setIconSize(QtCore.QSize(65, 30))
        self.pos_5_7.setObjectName("pos_5_7")
        self.pos_5_4 = QtWidgets.QPushButton(self.equal_5)
        self.pos_5_4.setGeometry(QtCore.QRect(20, 230, 81, 20))
        self.pos_5_4.setText("")
        self.pos_5_4.setIcon(icon1)
        self.pos_5_4.setIconSize(QtCore.QSize(65, 30))
        self.pos_5_4.setObjectName("pos_5_4")
        self.equal_6 = QtWidgets.QGroupBox(self.Gamespace)
        self.equal_6.setGeometry(QtCore.QRect(1000, 50, 121, 261))
        self.equal_6.setTitle("")
        self.equal_6.setObjectName("equal_6")
        self.pos_6_5 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_5.setGeometry(QtCore.QRect(0, 150, 20, 91))
        self.pos_6_5.setAcceptDrops(False)
        self.pos_6_5.setText("")
        self.pos_6_5.setIcon(icon)
        self.pos_6_5.setIconSize(QtCore.QSize(15, 80))
        self.pos_6_5.setAutoRepeat(False)
        self.pos_6_5.setAutoExclusive(False)
        self.pos_6_5.setObjectName("pos_6_5")
        self.pos_6_3 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_3.setGeometry(QtCore.QRect(100, 150, 20, 91))
        self.pos_6_3.setAcceptDrops(False)
        self.pos_6_3.setText("")
        self.pos_6_3.setIcon(icon)
        self.pos_6_3.setIconSize(QtCore.QSize(15, 80))
        self.pos_6_3.setAutoRepeat(False)
        self.pos_6_3.setAutoExclusive(False)
        self.pos_6_3.setObjectName("pos_6_3")
        self.pos_6_1 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_1.setGeometry(QtCore.QRect(20, 6, 81, 20))
        self.pos_6_1.setText("")
        self.pos_6_1.setIcon(icon1)
        self.pos_6_1.setIconSize(QtCore.QSize(65, 30))
        self.pos_6_1.setObjectName("pos_6_1")
        self.pos_6_6 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_6.setGeometry(QtCore.QRect(0, 30, 20, 101))
        self.pos_6_6.setAcceptDrops(False)
        self.pos_6_6.setText("")
        self.pos_6_6.setIcon(icon)
        self.pos_6_6.setIconSize(QtCore.QSize(15, 80))
        self.pos_6_6.setAutoRepeat(False)
        self.pos_6_6.setAutoExclusive(False)
        self.pos_6_6.setObjectName("pos_6_6")
        self.pos_6_2 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_2.setGeometry(QtCore.QRect(100, 30, 20, 101))
        self.pos_6_2.setAcceptDrops(False)
        self.pos_6_2.setText("")
        self.pos_6_2.setIcon(icon)
        self.pos_6_2.setIconSize(QtCore.QSize(15, 80))
        self.pos_6_2.setAutoRepeat(False)
        self.pos_6_2.setAutoExclusive(False)
        self.pos_6_2.setObjectName("pos_6_2")
        self.pos_6_7 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_7.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.pos_6_7.setText("")
        self.pos_6_7.setIcon(icon1)
        self.pos_6_7.setIconSize(QtCore.QSize(65, 30))
        self.pos_6_7.setObjectName("pos_6_7")
        self.pos_6_4 = QtWidgets.QPushButton(self.equal_6)
        self.pos_6_4.setGeometry(QtCore.QRect(20, 230, 81, 20))
        self.pos_6_4.setText("")
        self.pos_6_4.setIcon(icon1)
        self.pos_6_4.setIconSize(QtCore.QSize(65, 30))
        self.pos_6_4.setObjectName("pos_6_4")
        self.upload_question = QtWidgets.QPushButton(self.Gamespace)
        self.upload_question.setGeometry(QtCore.QRect(270, 390, 93, 28))
        self.upload_question.setObjectName("upload_question")
        self.generate_new = QtWidgets.QPushButton(self.Gamespace)
        self.generate_new.setGeometry(QtCore.QRect(390, 390, 93, 28))
        self.generate_new.setObjectName("generate_new")
        self.reset_button = QtWidgets.QPushButton(self.Gamespace)
        self.reset_button.setGeometry(QtCore.QRect(760, 390, 93, 28))
        self.reset_button.setObjectName("reset_button")
        self.equal_generate = QtWidgets.QPushButton(self.Gamespace)
        self.equal_generate.setGeometry(QtCore.QRect(510, 390, 93, 28))
        self.equal_generate.setObjectName("equal_generate")
        self.question_button.raise_()
        self.submit_button.raise_()
        self.line.raise_()
        self.mode_button.raise_()
        self.showanswer_button.raise_()
        self.equal_0.raise_()
        self.equal_1.raise_()
        self.equal_2.raise_()
        self.equal_3.raise_()
        self.equal_4.raise_()
        self.dengyu.raise_()
        self.equal_5.raise_()
        self.equal_6.raise_()
        self.upload_question.raise_()
        self.generate_new.raise_()
        self.reset_button.raise_()
        self.equal_generate.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #   background
        palette = QtGui.QPalette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap(":/newprefix2/metal.jpg")))
        self.setPalette(palette)


        self.retranslateUi(MainWindow)
        self.equal_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "火柴棍"))
        self.submit_button.setText(_translate("MainWindow", "确认提交"))
        self.question_button.setText(_translate("MainWindow", "选择关卡"))
        self.mode_button.setText(_translate("MainWindow", "选择模式"))
        self.showanswer_button.setText(_translate("MainWindow", "查看答案"))
        self.equal_2.setTabText(self.equal_2.indexOf(self.plus_minus), _translate("MainWindow", "加减"))
        self.sig_3_4.setText(_translate("MainWindow", "X"))
        self.equal_2.setTabText(self.equal_2.indexOf(self.mutiply), _translate("MainWindow", "乘"))
        self.upload_question.setText(_translate("MainWindow", "我要出题"))
        self.generate_new.setText(_translate("MainWindow", "生成新题目"))
        self.reset_button.setText(_translate("MainWindow", "重置"))
        self.equal_generate.setText(_translate("MainWindow", "生成等式"))

